### ISSUE TITLE
DL of musicbrainz data is broke

### ISSUE THREAD

**Issue by mabushey** [linuxserver/docker-musicbrainz#14]
I've tried maybe a dozen times over the last few months due to the "if this section fails try again later" part, but it never works:

```
[cont-init.d] 30-initialise-database: executing... 
fetching latest dump from musicbrainz, if this section fails try again later as musicbrainz dump may not be fully uploaded 
to their site
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64.9M  100 64.9M    0     0  10.5M      0  0:00:06  0:00:06 --:--:-- 13.5M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.4M  100 21.4M    0     0  5888k      0  0:00:03  0:00:03 --:--:-- 5887k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  122M  100  122M    0     0  11.3M      0  0:00:10  0:00:10 --:--:-- 13.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69.0M  100 69.0M    0     0  9945k      0  0:00:07  0:00:07 --:--:-- 13.7M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.2M  100 29.2M    0     0  7242k      0  0:00:04  0:00:04 --:--:-- 7243k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7126  100  7126    0     0   4111      0  0:00:01  0:00:01 --:--:--  4111
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 23 2124M   23  499M    0     0  13.3M      0  0:02:39  0:00:37  0:02:02 12.4M
curl: (56) Recv failure: Connection reset by peer
[cont-init.d] 30-initialise-database: exited 56.
```

What would it take to manually find and download the files first, and point the image at the Downloaded files? Has anyone successfully used this image? I have 100Mb Internet, but Musicbrainz goes down all the time, this is why I would love my own musicbrainz server.

**Comment by CHBMB** [comment]
Many people are successfully using this image.  Have you tried cleaning out the /config and /data folders between attempts?  I seem to recall that helping one person in the past.  

I'm not sure how manually downloading the files is going to help particularly, if there server is down when you try then there server is down when you try, regardless of which machine/client you're using to download with.

**Comment by mabushey** [comment]
Thanks for the response CHBMB.

> Many people are successfully using this image.

I suspect many more people are unsuccessfully using this image.

What finally worked was to delete everything in the `config` and `data` directories except for `data/import`, and to go into the `data/import/20160727-001648` and use wget: `wget ftp://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/20160727-001648/mbdump.tar.bz2`. I'm not sure why curl is broke but using wget succeeded the first time where as curl in the docker file always fails. Once downloaded, curl in the docker file tries to resume, and as it's already completed it happily continues. Wget has a `-N` flag for only get if newer, I think more of a proper fix is to replace curl with wget. Yes, I know curl should work, but at least on Debian it does not.

**Comment by sparklyballs** [comment]
"I suspect many more people are unsuccessfully using this image."

you suspect wrong.

**Comment by CHBMB** [comment]
I actually tried to pull this last night and it was successful, but like I said before if you've got a broken data set from previous attempts it will fail.

**Comment by mabushey** [comment]
As I stated, deleting the `config` and `data` directories did not work, the curl request for mbdump.tar.bz2 always fails (20 to 30 attempts, several of which involved starting from scratch). I fixed it by manually downloading it. I'm glad to hear it's at least working for some people.

sparklyballs: I really doubt it.

**Comment by sparklyballs** [comment]
lol, this container has nearly 27K pulls from the hub and we've had less than 20 reports of trouble of the same nature you're having.

you do the math.

**Comment by CHBMB** [comment]
mabushey, no one is denying that the musicbrainz site is temperamental to say the least, but I can't reproduce what you're seeing and have never had any problems providing the musicbrainz site is working.  I don't actually use this container myself, but I do pull it once in a while when someone does report problems to just check it works.

Bit of a pain really as it does take an awful long time to get up and running.

Like sparklyballs' has said, no one is denying that the occasional person doesn't have trouble but the inference that you don't believe it works for the majority of people is not the case I'm afraid.

Honestly, if that many people were struggling with it, we'd either fix it or remove the damn thing.

Anyways, glad to hear you got it up and running in the end.

**Comment by mabushey** [comment]
> Anyways, glad to hear you got it up and running in the end.

Thank you, it is working and all is good. I was just concerned that other people would run into the same problems I did. Thanks for your time responding to this issue, and thanks for the musicbrainz container! :)
