### ISSUE TITLE
A couple questions

### ISSUE THREAD

**Issue by nuentes** [linuxserver/docker-musicbrainz#15]
I'm pretty new to linux, newer to docker, and even newer to running a local musicbrainz slave, so very sorry if my questions are incedibly basic or dim.

So I believe replication is on and automated, correct?  Are search indexes already built, or do I need to build them?  According to the musicbrainz documentation, I'd need to run the following for that:

```
sudo su - search
bin/reindex
```

Lastly, how would I access the main database.  Again, the musicbrainz documentation says the following:

```
sudo su - musicbrainz
cd musicbrainz-server/admin
./psql READWRITE
```

Are these users included in the install (search / musicbrainz)?

**Comment by j0nnymoe** [comment]
Hi nuentes, the musicbrainz docker is designed to be a local mirror for something like beets to use.
If you wish to run those commands, you first need to get inside the container using the following command: `docker exec -it musicbrainz /bin/bash` then execute the commands.
