### ISSUE TITLE
Curl in stalling during downloads

### ISSUE THREAD

**Issue by Poag** [linuxserver/docker-musicbrainz#18]
OS- Unraid 6
Using the docker from Community Apps plugin.

The curl lines of the docker are hanging indefinately for unknown reasons, even from the unraid cli they hang. I edited the 30 script and replaced with wgets and it ran through fine, although i had to set the version by hand as the curl for the version also hangs.

My new get lines look like this

```
s6-setuidgid abc wget -P "$DUMP_DEST" "$DUMP_URL"/mbdump-cdstubs.tar.bz2
```

**Comment by sparklyballs** [comment]
i'm unable to reproduce, curl is working fine here.
possible you're not waiting long enough and curl doesn't have progress bar by default for the fetches.
