### ISSUE TITLE
Process for MusicBrainz schema upgrades

### ISSUE THREAD

**Issue by daj92109** [linuxserver/docker-musicbrainz#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
MusicBrainz updates are failing due to a DB schema change.  What is the recommended procedure to resolve this?  Download the Docker container from scratch?  It's probably worth noting this procedure in the README.md.

PS: I am unable to open an account on forum.linuxserver.io to ask this question.  The Captcha test always fails.

-- For reference here is my slave.log ---
Wed May 17 14:00:00 2017 : Downloading https://metabrainz.org/api/musicbrainz/replication-104468.tar.bz2 to /tmp/replication-104468.tar.bz2
Wed May 17 14:00:02 2017 : Decompressing /tmp/replication-104468.tar.bz2 to /tmp/loadrep-L8U9eK
TIMESTAMP
COPYING
README
REPLICATION_SEQUENCE
SCHEMA_SEQUENCE
mbdump/dbmirror_pending
mbdump/dbmirror_pendingdata
Wed May 17 14:00:02 2017 : This replication packet matches schema sequence #24, but the database is currently at #23
Wed May 17 14:00:02 2017 : You must upgrade your database in order to apply this replication packet

**Comment by sparklyballs** [comment]
currently working on schema 24 since monday, but for some reason there's a regression and no css is rendered.

the recommend method of update will be to clear config and data and reinitialise the database , ie clean install.
