### ISSUE TITLE
postgres problem

### ISSUE THREAD

**Issue by phynias** [linuxserver/docker-musicbrainz#42]
i have the latest image and i'm getting.
postgres: could not access the server configuration file "/config/postgresql.conf": No such file or directory

i saw that there were old issues that were closed. i think maybe something changed again.

**Comment by sparklyballs** [comment]
what os as the host ?
what type of mount point, ie local, network, array (unraid) 

etc 

without this information we cannot help you 
and the latest version was tested and works on a local machine by myself, prior to the commit being merged

**Comment by phynias** [comment]
centos7, local mount.

not sure what to say. start it and after a while it spams that. go into the container and there is no config for postgres at /config. i found it at /data/dbase/postgresql.conf

**Comment by j0nnymoe** [comment]
docker create/run command would help too. With musicbrainz, this container -can- take a long time to start up. I've always started the container then left it running over night on initial start up.

**Comment by wtf911** [comment]
there is definitely an issue with:
postgres: could not access the server configuration file "/config/postgresql.conf": No such file or directory

what i did was let the docker run overnight, found that in the logs in the morning, restarted the container and then it worked...but shouldn't have to restart it? idk

**Comment by baoshan** [comment]
Same error here:
`postgres: could not access the server configuration file "/config/postgresql.conf": No such file or directory`.

I’m hosting the container in macOS. Create the container via:

`docker create --name=musicbrainz -e BRAINZCODE=.... -p 5000:5000 -p 5432:5432 linuxserver/musicbrainz`

Do I need to specify `uid` or `gid` explicitly to solve the `/config/postgresql.conf` issue?

Thank you.

**Comment by baoshan** [comment]
I could confirm (at least for my current case), the `postgres` error was due to musicbrainz data dump downloading error. Check your console log to see it the download stage is successful or not.

**Comment by homerr** [comment]
Stale issue, closed.

**Comment by mabushey** [comment]
Can someone fix this?

**Comment by mabushey** [comment]
@baoshan That's probably one way. The Linuxserver musicbrainz container worked last year, but fails with every version I've tested in the last six months. It appears that stopping and starting makes this error go away, but still is a dead container other than some logs that end in:
```
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2019-06-10 13:54:32.641 PDT [372] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-06-10 13:54:32.641 PDT [372] LOG:  listening on IPv6 address "::", port 5432
2019-06-10 13:54:32.656 PDT [372] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
2019-06-10 13:54:32.667 PDT [372] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-06-10 13:54:32.966 PDT [400] LOG:  database system was shut down at 2019-06-10 13:52:14 PDT
2019-06-10 13:54:33.731 PDT [372] LOG:  database system is ready to accept connections
2019-06-10 14:00:01.451 PDT [435] ERROR:  relation "dbmirror_pending" does not exist at character 22
2019-06-10 14:00:01.451 PDT [435] STATEMENT:  SELECT COUNT(*) FROM dbmirror_pending
Mon Jun 10 14:00:01 PDT 2019 : LoadReplicationChanges failed (rc=255) - see /config/log/musicbrainz/slave.log
```

**Comment by NachtKind** [comment]
I had this Problem after switching the Virus-Scaner on in my Firewall. It just took to long to scan the downloaded Archives which are transfered over FTP. Switching that of did the thing. 

The latest Container works as a Charm.

version: "2"
services:
  musicbrainz:
    image: linuxserver/musicbrainz
    container_name: musicbrainz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - BRAINZCODE=XXX
      - WEBADDRESS=XXX.XXX.XXX.XXX
    volumes:
      - ./config/:/config:rw
      - ./data/:/data:rw
    ports:
      - 5000:5000
    restart: unless-stopped

**Comment by CHBMB** [comment]
@mabushey Open a new issue rather than necro bump.  Please include all the relevant info as well as the logs.
