### ISSUE TITLE
Better multi-cores support by extract nproc from the environment

### ISSUE THREAD

**Issue by baoshan** [linuxserver/docker-musicbrainz#48]
Thanks to the great team/community behind the project.

I intend to use a 16-cores environment to run the container. The container is used to serve high-parallel MusicBrainz API requests.

If the `--nproc` argument is designed to maximize throughput, I think it’s better to extract the number of processors from the environment. Possible via:

`grep -c ^processor /proc/cpuinfo`.

If that looks sane to you, do you prefer a PR, or I should expect an update later sometime? Thank you.

**Comment by CHBMB** [comment]
Why not use `--cpuset-cpus` as part of your docker run command?

**Comment by baoshan** [comment]
Thank you for the suggestion! I think `--cpuset-cpus` can not change the fact of max `--nproc 5` parallel processes hard set in below:

```
exec \
	s6-setuidgid abc plackup -I lib -s FCGI \
	-E deployment --port 55901 --nproc 5 \
```

Please blame me if my concept is wrong.

**Comment by CHBMB** [comment]
Oh, got you!.....

@sparklyballs is the author so I'm going to leave it to him to look at this one, I didn't quite understand what you were suggesting, much clearer now!

**Comment by baoshan** [comment]
Thank you @CHBMB! Actually it’s very embarrassing for somebody who understand little but want more to open an issue.

**Comment by sparklyballs** [comment]
i've opted for an env var NPROC to allow user setting of the value rather than assigning it based on cpus on host etc

if user has multiple containers setting it that way could hog resources

**Comment by baoshan** [comment]
I’d love your suggestion. Thanks @sparklyballs.
