### ISSUE TITLE
Stability issue under high load

### ISSUE THREAD

**Issue by baoshan** [linuxserver/docker-musicbrainz#51]
When the container is under high load (parallel requests of APIs) for hours, below pattern of errors start to rise (which is reproducible). The requests fail, and it seems only a restart can bring the server back to online.

```
error: cannot stat /dev/stdin: Stale file handle
./run: line 5:   332 Killed                  s6-setuidgid abc redis-server /config/redis.conf
./run: line 5: 13754 Killed                  s6-setuidgid abc redis-server /config/redis.conf
./run: line 5: 32268 Killed                  s6-setuidgid abc redis-server /config/redis.conf
./run: line 5: 32709 Killed                  s6-setuidgid abc redis-server /config/redis.conf
./run: line 5:   695 Killed                  s6-setuidgid abc redis-server /config/redis.conf
./run: line 5:  1444 Killed                  s6-setuidgid abc redis-server /config/redis.conf
./run: line 5:  1613 Killed                  s6-setuidgid abc redis-server /config/redis.conf
./run: line 5:  1663 Killed                  s6-setuidgid abc redis-server /config/redis.conf
......
```

I’m not sure it’s a MB server issue, or it’s a potential issue of this project. Could someone kindly guide me to a way to resolve the issue?

**Comment by thelamer** [comment]
The stale file handle would indicate that the container ran out of inodes to allocate. 

What is your host OS ? If you are running AUFS (notorious for inode usage) for your docker storage driver try bumping up to overlay2 (might require a kernel upgrade) 

Checkout here for information on storage drivers: 

https://docs.docker.com/engine/userguide/storagedriver/selectadriver/

**Comment by baoshan** [comment]
Thanks for your insight!

I’m hosting the container under macOS. Do you think moving to a Linux machine may solve my issue?

**Comment by thelamer** [comment]
I mean this is just a guess given the error message, what is actually happening is the redis-server is crashing and being restarted. 

You can change to overlay2 in OSX as it uses a VM to in Hyperkit to actually run your Docker Environment. 

Got to the Docker icon > "Preferences" > "Daemon" > "Advanced" and set the storage-driver to overlay2

You will need to regenerate the docker containers if you do this, but if you bind mounted everything outside of the container it should not be an issue. 

Another thing to check is if your docker allocated space is running out: 

```
df -h
```
The entry for docker will be under /etc/hosts

You can cleanup docker junk by running: 
```
docker system prune
```

This will clear out dangling images volumes and unused networks etc. 

Edit: and ram usage, check your ram usage when this is happening.

**Comment by homerr** [comment]
Stale, closed
