### ISSUE TITLE
memory leaks lead to unresponsive server

### ISSUE THREAD

**Issue by a3rosol** [linuxserver/docker-musicbrainz#60]
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-38-generic x86_64)

snippet from docker compose:
  musicbrainz:
    image: linuxserver/musicbrainz
    container_name: musicbrainz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Europe/London"
      - BRAINZCODE=#######
    networks:
      - addServices
    volumes:
      - /home/#/docker/musicbrainz/config:/config
      - /home/#/docker/musicbrainz/data:/data
    ports:
      - "127.0.0.1:5885:5000"

usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-brainzcode: executing... 
[cont-init.d] 20-brainzcode: exited 0.
[cont-init.d] 30-initialise-database: executing... 
[cont-init.d] 30-initialise-database: exited 0.
[cont-init.d] 35-generate_css: executing... 
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[17:12:28] Using gulpfile /app/musicbrainz/gulpfile.js
[17:12:28] Starting 'default'...
(node:278) Warning: Possible EventEmitter memory leak detected. 12 resolve listeners added. Use emitter.setMaxListeners() to increase limit
[17:12:52] Finished 'default' after 24 s
[cont-init.d] 35-generate_css: exited 0.
[cont-init.d] 40-config: executing... 
[cont-init.d] 40-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
LOG:  database system was interrupted; last known up at 2018-11-04 16:57:38 GMT
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 3/4CDEEA48: wanted 24, got 0
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

no symlinks

please look at `(node:278) Warning: Possible EventEmitter memory leak detected. 12 resolve listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by tobbenb** [comment]
If it's a memory leak in musicbrainz there is not much we can do about it.

**Comment by homerr** [comment]
Please let us know if you come across something in the container that we may be able to fix but as @tobbenb said it looks more like an issue in musicbrainz that may need their assistance to be solved.
