### ISSUE TITLE
Why so slow ?

### ISSUE THREAD

**Issue by lucacalcaterra** [linuxserver/docker-musicbrainz#64]
Hi, in every test of my local musicbrainz docker (various hardware) , noticed that query response are quite slow the first time and faster the second (probably because cache).

Also the VirtualBox VM has the same issue...

So, in this way local server is slower than online musicbrainz... it's a problem of the docker container or the Musicbrainz server self  architecture  ?

Thanks,

Luca

**Comment by tobbenb** [comment]
If it's the same with the Virtualbox vm, then it's musicbrainz that need to look at that issue.
Not much we can do about it, as we just package it in a container
