### ISSUE TITLE
Search server is not packaged

### ISSUE THREAD

**Issue by thresheek** [linuxserver/docker-musicbrainz#70]
Musicbrainz server relies on lucene-based java search server and indexes; however it doesnt seem to be packaged in the image.  It is needed to offload searches from a public musicbrainz server, and poses a significant security risk of leaking data your musicbrainz mirror serves.

**Comment by tobbenb** [comment]
I don't follow you. It's not clear at all what the security risk is.
This container is meant to be used as an local mirror of musicbrainz,not a public facing mirror.

**Comment by tdfischer** [comment]
I believe what @thresheek is referring to is that if you run a search in, e.g. beets, the search still goes out to the official MusicBrainz servers which has the result of revealing your search activity to their infrastructure.

But they do bring up an actionable problem which is that the search is not included in the container. This means I'm still ratelimited to 1 search per second, even if I've gone through the trouble of downloading gigs of data to setup a local mirror. The bottleneck for me isn't downloading database records or album covers over my internet connection, its that 1 second ratelimit.

**Comment by slayer49** [comment]
doesn't this commit build the build search server?

https://github.com/linuxserver/docker-musicbrainz/commit/432a845dc285f64af86cb755f80d7a9e4ee00131

**Comment by tdfischer** [comment]
Not at all. The search indexes are at least 20GB and they're never
downloaded, nor does the image run solr, the actual search service.
Downloading the indexes is optional, of course, but it then takes 4.5
hours on 16 threads and 16GB of RAM.

https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev#build-search-indexes

If this image does support solr, then there is no documentation on how
to download or rebuild the indexes, or how to disable the internal
proxy.

**Comment by slayer49** [comment]
This image supports the old search server.  There is a seperate dockerfile to build it which i linked to above.  The new search server based on Solr was just merged into musicbrainz master on 5-14-2020.  Hopefully this image can get updated to that eventually.

https://github.com/metabrainz/musicbrainz-docker/releases
