### ISSUE TITLE
Postgres database configuration steps?

### ISSUE THREAD

**Issue by boredazfcuk** [linuxserver/docker-musicbrainz#71]
Hi,
I've been trying to get this container working on and off for a couple of days now, but I'm not getting anywhere fast.

It first complained about no /data/dbase/postgres.conf file. I found one in a folder called music-brainz-test (or something similar) and copied that to /data/dbase. That fixed that error, but then it complained about a missing PG_VERSION. I manually created that one and then it complained about postgresql.auto.conf... I quickly realised that it doesn't come with an empty DB pre-installed.

I set up a postgres db from their official image, shut it down, and then mounted the empty database to the /data/dbase folder in the MB container. MB then complained about the role 'abc' not existing. I tried to connect to the postgres db it errors out complaining about it already running (and I can't kill it without the container restarting).

It seems as though the MusicBrainz container doesn't come with a vanilla DB configured to be able to import the db dump. Surely I'm not the only person seeing this?

Running Debian Buster on an  i5 3.2GHz with bind mounts for volumes (no links).

Any pointers would be greatly appreciated.

**Comment by pl77** [comment]
I encountered this issue when running this container again after not using it for months.  Initially the complaint was that I was using PostgreSQL 9.6, so I wiped the old database directory as well as all configuration files.  Then, when using the ```docker-compose up -d``` command I received the missing `postgresql.conf` file error mentioned here.  I did have an old backup `postgresql.conf` file that I put back in the config directory and it worked after that. Once I provided it a postgresql.conf file it downloaded all the backup files, created a database, and then populated it.

I don't know why your container isn't generating the database.  Did you give it a data directory `--volume=` location for it to store persistent data?  If you did, did you make sure to set the correct permissions?  It's very picky about needing the PostgreSQL directory to be 0700 permissions to the user id identified in the docker-compose file, not world-readable.  It won't start the database without that.  

EDIT: @sparklyballs or @thelamer : perhaps the image can include a default or template `postgresql.conf` file?  Or did I make a mistake that caused it not to generate one automatically?

**Comment by boredazfcuk** [comment]
> 
> 
> I encountered this issue when running this container again after not using it for months. Initially the complaint was that I was using PostgreSQL 9.6, so I wiped the old database directory as well as all configuration files. Then, when using the `docker-compose up -d` command I received the missing `postgresql.conf` file error mentioned here. I did have an old backup `postgresql.conf` file that I put back in the config directory and it worked after that. Once I provided it a postgresql.conf file it downloaded all the backup files, created a database, and then populated it.
> 
> I don't know why your container isn't generating the database. Did you give it a data directory `--volume=` location for it to store persistent data? If you did, did you make sure to set the correct permissions? It's very picky about needing the PostgreSQL directory to be 0700 permissions to the user id identified in the docker-compose file, not world-readable. It won't start the database without that.
> 
> EDIT: @sparklyballs or @thelamer : perhaps the image can include a default or template `postgresql.conf` file? Or did I make a mistake that caused it not to generate one automatically?

I worked out what is causing this. The ENV URL_ROOT needs to be changed to http:// so that the curl commands work correctly.

**Comment by boredazfcuk** [comment]
Fixed by pull request #73, thanks.

Closed.
