### ISSUE TITLE
MusicBrainz logo on readme is outdated

### ISSUE THREAD

**Issue by reosarevok** [linuxserver/docker-musicbrainz#75]
Hi!

The project readme (and possibly other places) use the old MusicBrainz logo. Updated ones are at
https://github.com/metabrainz/metabrainz-logos/tree/master/final-logos-v2/MusicBrainz/VECTOR 
/ https://github.com/metabrainz/metabrainz-logos/tree/master/final-logos/MusicBrainz/VECTOR in case you feel like updating it! (I'd send a PR but it seems to be stored in an archived repo).

Nicolás from MusicBrainz

**Comment by nemchik** [comment]
The places it would need to be updated are https://github.com/linuxserver/docker-musicbrainz/blob/defc2c7ebdb91e0bae2be3db6c8022df3bceff1a/readme-vars.yml#L6 (you can add their logo to the top level folder of this repo and update the URL to point to this repo, ex: https://github.com/linuxserver/docker-limnoria/blob/9fcc9983236fb7860c2e5b174aa0a8c5579fa25b/readme-vars.yml#L6 referring to the logo in the same repo)

and https://github.com/linuxserver/docker-templates/blob/master/linuxserver.io/img/musicbrainz-icon.png (which is referenced by https://github.com/linuxserver/docker-templates/blob/1232374eb0d4e26bb8c1458d174d1a03a600809e/linuxserver.io/musicbrainz.xml#L59 but you don't need to edit that).

**Comment by reosarevok** [comment]
Thanks! Submitted both updates, sorry it took forever :)

**Comment by reosarevok** [comment]
Do you need anything else from me here?
