### ISSUE TITLE
LOOKING FOR A MAINTAINER

### ISSUE THREAD

**Issue by aptalca** [linuxserver/docker-musicbrainz#86]
We are looking for a community maintainer for this image.

The latest updates (and rebase to alpine 3.12) seem to have cause some issues for existing users and the team members don't have the bandwidth or the interest in fixing and maintaining this image.

Anyone interested can reach out here or on our discord. If we are unable to find a maintainer within the next few weeks, this image will be deprecated.

Thanks

**Comment by j0nnymoe** [comment]
Closing as this container has now been depreciated.
